- DiffusionPreprocessing/scripts/basic_preproc.sh
The recent name change of base_pos and base_neg broke the following merge commands:
${FSLDIR}/bin/fslmerge -t ${rawdir}/Pos `echo ${rawdir}/${basePos}*.nii*`
${FSLDIR}/bin/fslmerge -t ${rawdir}/Neg `echo ${rawdir}/${baseNeg}*.nii*`
The former now merge not only Pos_[0-9].nii.gz, but also Pos_b0.nii.gz. This causes the resulting Pos_Neg.nii.gz to contain duplicate b0s and hence crashes eddy. I have adjusted the command to fix this.
> Don't include b0 files in merging of final data

- Examples/Scripts/PreFreeSurferPipelineBatch.sh
- PreFreeSurfer/PreFreeSurferPipeline.sh
- PreFreeSurfer/scripts/T2wToT1wDistortionCorrectAndReg.sh
- fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
- global/scripts/TopupPreprocessingAll.sh
This will allow for pulling values directly from BIDS-style sidecar json files, without needing to remap the axes into the x/y/z nomenclature.
> Add capability to use BIDS convention (i/j/k) for specifying axes

- Examples/Scripts/FreeSurferPipelineBatch.sh
* Fix Issue #100
* Remove use of --printcom= flag in example script
* This should go in the next release whether it is a bugfix release (e.g. v4.0.1) or a new feature release
> Removed --printcom= option from FreeSurferPipelineBatch.sh

- MSMAll/scripts/MSMAll.sh
- MSMAll/scripts/SingleSubjectConcat.sh
Fixed problem with not properly setting up MATLAB path to include the `${HCPPIPEDIR}/global/matlab` directory when invoking interactive MATLAB.
> Corrected use of path for interpreted MATLAB usages

- Examples/Scripts/DeDriftAndResamplePipelineBatch.sh
Fixing name of flag used in `DeDriftAndResamplePipelineBatch.sh` script.
`--multirun-fix-concat-name=` becomes `--multirun-fix-concat-names` in invocation of `DeDriftAndResamplePipeline.sh`
> Fixed multirun-fix-concat-names flag in example batch script

- DiffusionPreprocessing/scripts/run_eddy.sh
Removed the not needed underscore in variable name: "g_gpu_EnabledEddy" should be "g_gpuEnabledEddy"
> Fixed variable name typo (eddy_cuda variable)

- DeDriftAndResample/DeDriftAndResamplePipeline.sh
- MSMAll/README.md
This has not been tested.
DeDriftAndResample doesn't appear to actually detect NONE for the dedrift files option, instead it detects whether the regname and concatregname are the same.  I have therefore made both concateregname and dedrift files optional (if unset, concat regname gets set to regname).
This also makes additional edits to the msmall readme which @mharms and I discussed here:
https://github.com/Washington-University/HCPpipelines/commit/9f003a56b321608cd53a2474dd898b7a172ffe37#commitcomment-33644720
> Make dedrift and concat regname optional in DeDriftAndResample

- Examples/Scripts/SetUpHCPPipeline.sh
- global/scripts/RSNregression.m
- global/scripts/RSNregression.sh
- global/scripts/finish_hcpsetup.shlib
- global/scripts/log.shlib
- global/scripts/newopts.shlib
In order to code up the new RSN script in a style I consider better, I had to write some new option parsing functions and make some edits to the setup script (to set $PATH as previously discussed).  The end of the setup script now sources something from global/scripts, which contains some bits that the user should never need to edit, but that pipeline maintainers may want to update - this way, in the future, updating the pipelines can add some variables to the user's effective setup without the user needing to restart from the template version again.  Since existing users will need at least a few lines from my new version of the setup script to run this new script, this is an attempt to reduce future occurrences of this situation (it could be argued that some more of the sanity checking …
> initial new script for RSN regression, new option parsing shlib, edits to template setup script to allow some reliance on PATH

- fMRISurface/scripts/CreateDenseTimeseries.sh
- fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
- fMRIVolume/scripts/IntensityNormalization.sh
- fMRIVolume/scripts/OneStepResampling.sh
This PR is intended to address #132.  This functionality is a necessary addition before we start HCP-D/A processing.
Some minor readability improvements and comment additions are included for the affected scripts as well.
> Add assessment of spatial coverage within both fMRIVolume and fMRISurface

- FreeSurfer/FreeSurferPipeline-v5.3.0-HCP.sh
- FreeSurfer/FreeSurferPipeline.sh
- FreeSurfer/scripts/FreeSurferHiresPial.sh
- FreeSurfer/scripts/FreeSurferHiresWhite.sh
The parameter has the same functionality as in the PreFreeSurfer pipeline. And is related to the MPP version checking, which in this case only checks for the presence of T2w image.
If T2w image is set to NONE and legacy MPP version is selected then:
* `-T2` option is excluded from `recon_all_cmd`
* `-T2pial` is replaced with `-noT2pial`  in `recon_all_cmd`
* Making T2w to T1w registration available in FSL format section is skipped
* `make_t2w_hires_nifti_file` and `make_t1wxtw2_qc_file` is skipped
Switch from tabs to spaces and remove trailing line spaces
Switching from tabs to spaces, removing trailing spaces in lines
When T2wImage is set to NONE, operations that depend on the presence of T2wImage are skipped.:
* creation of normalized T2w image
* generation of pial first surface with T2 …
> FreeSurfer Pipeline related pull request

- PreFreeSurfer/PreFreeSurferPipeline.sh
- PreFreeSurfer/scripts/ACPCAlignment.sh
- PreFreeSurfer/scripts/AtlasRegistrationToMNI152_FLIRTandFNIRT.sh
- PreFreeSurfer/scripts/BiasFieldCorrection_T1wOnly.sh
- PreFreeSurfer/scripts/BiasFieldCorrection_sqrtT1wXT1w.sh
- PreFreeSurfer/scripts/BrainExtraction_FNIRTbased.sh
- PreFreeSurfer/scripts/T2wToT1wDistortionCorrectAndReg.sh
- PreFreeSurfer/scripts/T2wToT1wReg.sh
Changed tabs to spaces amd removed spaces at end of lines
The parameter has the followinig possible values:
* hcp -> enable only strict HCP pipelines functionality (the default if the parameter is not specified)
* legacy -> enable extended pipelines functionality to work with legacy datasets
A check is performed based on this parameter. If ‘hcp’ is specified then the script ends with an error if:
* T2w input image is specified as NONE
* a custom brain / brain mask is used
The check is performed and logged before any processing is started, with explicit warning that the use does not conform to Glasser et al. (2013) paper when ‘legacy’ option is used.
The parameter has the following possible values:
* NONE -> do not use a custom brain (the default if the parameter is not provided)
* CUSTOM …
> PreFreeSurfer Pipeline related pull request

- fMRISurface/GenericfMRISurfaceProcessingPipeline.sh
- fMRISurface/GenericfMRISurfaceProcessingPipeline_1res.sh
Changing tabs to spaces, removal of trailing line spaces 
Changing tabs to spaces, removal of trailing line spaces
> fMRISurface related pull request

- FreeSurfer/FreeSurferPipeline.sh
- FreeSurfer/custom/conf2hires
- FreeSurfer/custom/recon-all.v6.hires
This will hopefully deal with the file handling issues of using a FLAIR acquisition within recon-all, but note that per `recon-all.v6.hires`:
`# - Might run with FLAIR instead of T2, but this has not been tested.`
So caveat emptor.
> Add capability to use FLAIR style acquisitions within FreeSurferPipeline.sh

- DiffusionPreprocessing/scripts/DiffusionToStructural.sh
- DiffusionPreprocessing/scripts/eddy_postproc.sh
The voxels inside the FOV at the first b0 might not be included in some other volumes due to movement. In eddy the signal these voxels, which are not included in all the volumes, are set to zero. In the HCP pipeline the output of eddy is resampled to T1 space. During this resampling, these voxels become non-zero due to the spline interpolation and are included within the final nodif_brain_mask.
This patch fixes this by:
1. Creating a mask which includes only those voxels consistently within the FOV across all volumes as determined by eddy (called fov_mask). This mask is created from the eddy (or eddy_combine) output before resampling. 
2. Transforming this mask to T1-weighted space using trilinear interpolation. This is then thresholded at a value of 1, so that any voxel which are at the …
> Fix diffusion mask in voxels outside the FOV

- ICAFIX/scripts/functionhighpassandvariancenormalize.m
- ICAFIX/scripts/icaDim.m
- ICAFIX/scripts/pca_dim.m
This pull request improves the accuracy and stability of dimensionality estimation for MR+FIX and related code.  In particular, the pca_dim.m function now aligns with the implementation in melodic, dimensionality is now estimated using the full set of normalized eigenvalues, rather than just the left most when using multiple Wishart distributions (i.e. the left most eigenvalues >1 are padded with ones to match the original number of eigenvalues), and when using multiple Wishart distributions a single overall Wishart distribution is fit to the estimated null eigenvalues for the purposes of the pca_dim.m estimation.  Also, two new modes of convergence are now available for icaDim.m including -1, which converges when the incremental change in dimensionality estimate is less that 0.25, and …
> *Bugfix and improvements to dimensionality estimation

- ICAFIX/ReApplyFixMultiRunPipeline.sh
- ICAFIX/ReApplyFixPipeline.sh
- ICAFIX/hcp_fix
- ICAFIX/hcp_fix_multi_run
With the forthcoming FIX version "1.06.12", we can now properly implement HP filtering in the MotionRegression=FALSE condition within single-run FIX.  This PR checks for the FIX version, and calls `fix` appropriately based on the FIX version.
This should resolve #108.
> Update hcp_fix to support the MotionRegression=FALSE condition

- ICAFIX/hcp_fix_multi_run
Regress sICA noise components out of movement regressors to enable their use on sICA+FIX cleaned fMRI data.  The files are present in text and .nii.gz formats and for both the concatinated and single runs
> Enable Creation of Cleaned Movement Regressors

- ICAFIX/hcp_fix_multi_run
This fixes a bug in #164 if `ConcatFolder` is not specified as an absolute path. And implements a suggestion that @coalsont had regarding the `tail` command.  It has been tested.
> Bug fix to cleaned movement regressor code, plus minor simplification

- PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh
With these changes, it will now report separately for each structure, and include additional info regarding overlap with the Atlas ROIs.
Example output file (from the same subject that prompted us to add this report in the first place):
```
Structure,nMissingBrainMaskFromAtlas,nMissingROIFromAtlas,nROIOverlapAtlas,nROIOutsideAtlas
ALL,409,,,
CEREBELLUM_LEFT,155,1304,7405,957
THALAMUS_LEFT,0,217,1071,203
CAUDATE_LEFT,0,303,425,96
PUTAMEN_LEFT,0,606,454,120
PALLIDUM_LEFT,0,129,168,110
BRAIN_STEM,19,468,3004,183
HIPPOCAMPUS_LEFT,28,317,447,139
AMYGDALA_LEFT,44,163,152,87
ACCUMBENS_LEFT,0,89,46,32
DIENCEPHALON_VENTRAL_LEFT,0,150,556,98
CEREBELLUM_RIGHT,81,1279,7865,914
THALAMUS_RIGHT,0,268,980,149
CAUDATE_RIGHT,0,332,423,114
PUTAMEN_RIGHT,0,359,651,102
PALLIDUM_RIGHT,0,93,167,95 …
```
> Extend the checking of the subcortical segmentation

- global/scripts/RSNregression.m
- global/scripts/RSNregression.sh
Enable a new 'single' mode of temporal regression for RSNRegression to enable applying existing results to a new CIFTI space or single regression in other contexts
> Enable Single Regression in RSNRegression

- fMRIVolume/scripts/MotionCorrection.sh
- fMRIVolume/scripts/OneStepResampling.sh
- global/scripts/tempfiles.shlib
This cannot be used by the public yet (not easily, anyway), as the -volume-resample command is not released, nor is the control of volume output datatype (added to resolve a considerable file size change between applywarp and wb_command output), so it is disabled by default.  Currently, enabling it requires editing the GenericfMRIVolume pipeline.
Once workbench has a new release, it can be made the default, or the fslsplit/loop/fslmerge code can be removed entirely.
> workbench implementation for OneStepResampling.sh

- DiffusionPreprocessing/DiffPreprocPipeline.sh
- DiffusionPreprocessing/DiffPreprocPipeline_Eddy.sh
- DiffusionPreprocessing/DiffPreprocPipeline_PostEddy.sh
- DiffusionPreprocessing/DiffPreprocPipeline_PreEddy.sh
- DiffusionPreprocessing/scripts/DiffusionToStructural.sh
- DiffusionPreprocessing/scripts/basic_preproc.sh
- DiffusionPreprocessing/scripts/basic_preproc_best_b0.sh
- DiffusionPreprocessing/scripts/basic_preproc_norm_intensity.sh
- DiffusionPreprocessing/scripts/basic_preproc_sequence.sh
- DiffusionPreprocessing/scripts/eddy_postproc.sh
- DiffusionPreprocessing/scripts/run_eddy.sh
- DiffusionPreprocessing/scripts/run_topup.sh
- global/config/best_b0.cnf
- global/scripts/select_dwi_vols
Here is a proposed piece of code to identify the bad b0's. The new code below extracts all b0's and runs topup (with the configuration file set for quick convergence). After topup each b0 is then scored based on its average square residual from the average b0.
The next step is to decide how to use these b0's in the later analysis. My proposal is to:
1. Identify the acquisition block with the highest quality initial b0. Merge all the data starting with that acquisition block (rather than starting with whatever acquisition block happened to be the first positive one that the user provided).
2. Merge the first b0 of the first block with the best b0 out of the corresponding block with opposite phase encoding. Run topup on just these two. Using two b0's should be fine as we already confirmed …
> Don't use motion-corrupted b0's in topup

- DiffusionPreprocessing/scripts/run_eddy.sh
This PR should make the automatic detection of the GPU-enabled version of `eddy` a bit more robust.
> Change eddy cuda assumptions

- DiffusionPreprocessing/DiffPreprocPipeline.sh
- DiffusionPreprocessing/DiffPreprocPipeline_Eddy.sh
- DiffusionPreprocessing/DiffPreprocPipeline_PostEddy.sh
- DiffusionPreprocessing/DiffPreprocPipeline_PreEddy.sh
Passes on the --no-gpu and --cuda-version flag from DiffPreprocPipeline.sh to DiffPreprocPipeline_Eddy.sh.
Also contains two other minor fixes:
- replaces some tabs with spaces, so that they are not mixed together
- only print no_gpu when running DiffPreprocPipeline_Eddy.sh if no_gpu has actually been set to something
> Pass on gpu options

- DiffusionPreprocessing/scripts/eddy_postproc.sh
- global/scripts/average_bvecs.py
It seems like this was never actually supported
> Support CombineDataFlag of 0 when averaging rotated bvecs

- Examples/Scripts/GenericfMRISurfaceProcessingPipelineBatch.sh
Fixed typo and made a variable name consistent between VolumeProcessingPipelineBatch and SurfaceProcessingPipelineBatch
> Fixed variable name typo

- DiffusionPreprocessing/scripts/run_eddy.sh
This error is raised when "run_eddy.sh" is looking for a GPU enabled eddy to run. If eddy and eddy_openmp are identical, this means that the search has failed. The new error message explains what the user might do about that.
> Clarify error message if eddy and eddy_openmp are identical

- FreeSurfer/FreeSurferPipeline.sh
FreeSurferPipeline.sh does not need explicit code for setting the number of cores.
The deleted code in the PR actually results in undesired behavior on the WU SLURM system. (i.e., "-openmp 8" is getting set).
If someone still wants to set the "-openmp" flag in the call to `recon-all`, they can use the `--extra-reconall-arg` flag.  Additionally, the `OMP_NUM_THREADS` environment variable is available.
> Remove old num_cores related code from FreeSurferPipeline.sh

- DiffusionPreprocessing/scripts/basic_preproc_best_b0.sh
This is a bug fix, which reverses the change  made in the last commit, which took isodd out.
That removal was not desired, because isodd is actually being used in this script.
> Puts isodd function back into the script

- Examples/Scripts/IcaFixProcessingBatch.sh
- Examples/Scripts/ReApplyFixProcessingBatch.sh
- ICAFIX/PostFix.sh
- ICAFIX/ReApplyFixMultiRunPipeline.sh
- ICAFIX/config/legacy.conf
- ICAFIX/hcp_fix_multi_run
- ICAFIX/scripts/Compile_MATLAB_code.sh
- ICAFIX/scripts/functionhighpassandvariancenormalize.m
- global/matlab/icaDim/icaDim.m
- global/scripts/log.shlib
- global/scripts/newopts.shlib
- global/scripts/processingmodecheck.shlib
Expose number of wisharts and make a melodic-like mode for icaDim, update example scripts to match.
> MR FIX legacy data

- MSMAll/MSMAllPipeline.sh
It was not flexible to add/remove arguments in the original location-based argument parsing. Tim's newopt library is a lifesaver. In addition to the argument part, the original script used `MSMAllRegs` to store the arguments for the main script MSMAll.sh, which is not necessary. 
- replace the location-based argument parsing with newopt;
- remove the logic related to `MSMAllRegs`;
- add optional arguments to set default file locations and default parameters such as `ICAdim`, `IterationModes`, `method`, etc.;
One subject with resting state fMRI is evaluated on the original version of MSMAllPipeline and this latest version. The results are identical.
> replace old argument parse in MSMAllPipeline with Tim's newopt

- DiffusionPreprocessing/scripts/basic_preproc_norm_intensity.sh
- DiffusionPreprocessing/scripts/basic_preproc_sequence.sh
- DiffusionPreprocessing/scripts/eddy_postproc.sh
This pull request pertains to issue #246 (https://github.com/Washington-University/HCPpipelines/issues/246).
> Made imrm calls at two locations in the Diffusion pipeline more robust and immune to the bug in FSL 6.0.6.2

- MSMAll/MSMAllPipeline.sh
- MSMAll/scripts/SingleSubjectConcat.sh
Previously the script `SingleSubjectConcat.sh` doesn't enable the frame range selection for each fMRI runs. Hence, the MSMAll is limited to be only applied to the full timeseries. 
- replace the old opt with Tim's newopt library in `SingleSubjectConcat.sh`;
- remove the bias correction and computation of VN files in `SingleSubjectConcat.sh`;
- add two optional arguments `StartFrame` and `EndFrame` in `SingleSubjectConcat.sh` and `MSMAllPipeline.sh`;
- validate the input frame range and throw an error if invalid range is provided in `SingleSubjectConcat.sh`;
One subject with resting state fMRI is evaluated. No error.
> update SingleSubjectConcat with frame selection; update MSMAll pipeline

- global/scripts/MyelinMap_BC.sh
Previously the scripts `MSMAll.sh`, `DeDriftAndResamplePipeline.sh` has repeated code blocks for generating the MyelinMap_BC files. The script `CreateMyelinMaps.sh` generated the same files based on GIFTI files. An abstract module is needed.
- generate the MyelinMap_BC file given an input mesh and an output mesh
- the input mesh and output mesh can be `native`, `164k`, `32k`
- An option `--use-ind-mean` is provided to match the reference map's mean with the individual map's mean value
- An option `RegName` is provided if the files to use is after registration such as `MSMAll`
Not done yet.
> add myelin map BC module

- global/scripts/average_bvecs.py
Since numpy 1.20.0, ["np.int" is no longer supported](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations). Instead, the python "int" can be used to replace "np.int" without changing the behavior. A user reported this [issue](https://groups.google.com/a/humanconnectome.org/g/hcp-users/c/7ewa-Wxp-kM) in the HCP users group.
- replace "np.int" with "int" in `global/scripts/average_bvecs.py`
The user has tested this new setting and fixed the bug.
> fix np.int deprecation issue

- DeDriftAndResample/DeDriftAndResamplePipeline.sh
Previously the script `DeDriftAndResamplePipeline.sh` doesn't use newopt and has code block that can be replaced with the new module `global/scripts/MyelinMap_BC.sh`.
- replace the old opt with the newopt library in `DeDriftAndResamplePipeline.sh`;
- replace _BC generation in `DeDriftAndResamplePipeline.sh` with the module `MyelinMap_BC.sh`;
Test is passed on a HCD subject. 
launch script: `/media/myelin/alex/MSMAll_optimization/DeDriftAndResamplePipelineBatch.sh`
log output without error:
`/media/myelin/alex/MSMAll_optimization/DeDriftAndResamplePipeline.sh.o770799`
> replace _BC with MyelinMap_BC module in DeDriftAndResamplePipeline.sh

- DeDriftAndResample/DeDriftAndResamplePipeline.sh
- Examples/Scripts/DeDriftAndResamplePipelineBatch.sh
The `Examples/Scripts/DeDriftAndResamplePipelineBatch.sh` doesn't set the correct argument of high pass value, and as a result the `DeDriftAndResample/DeDriftAndResamplePipeline.sh` was wrongly updated about this argument.
replace the `--highpass` with `--high-pass` to stay consistency of the same argument in the other scripts, e.g. ICAFix, MSMAll.
> fix the high pass argument

- DeDriftAndResample/DeDriftAndResamplePipeline.sh
- Examples/Scripts/DeDriftAndResamplePipelineBatch.sh
- global/scripts/MyelinMap_BC.sh
- The example script was not updated with the new mandatory argument "--msm-all-templates".
- MyelinMap_BC is only applied to MyelinMap and is not applied to a given map name, e.g. 'SmoothedMyelinMap'.
- Add the template argument and the variable to the example script `Examples/Scripts/DeDriftAndResamplePipelineBatch.sh`.
- Fix MyelinMap_BC and the reference in `DeDriftAndResamplePipeline.sh`
/media/myelin/alex/MSMAll_optimization/DeDriftAndResamplePipeline.sh.o3003663
/media/myelin/alex/MSMAll_optimization/DeDriftAndResamplePipeline.sh.e3003663
without error
> fix DeDriftAndResample and MyelinMap_BC module

- global/scripts/MyelinMap_BC.sh
The area files should be loaded from low resolution T1w folder instead of the low resolution folder in atlas space folder.
Now they are fixed.
> fix typo in MyelinMap_BC module

- DeDriftAndResample/DeDriftAndResamplePipeline.sh
- Examples/Scripts/DeDriftAndResamplePipelineBatch.sh
- Examples/Scripts/MSMAllPipelineBatch.sh
- Examples/Scripts/PostFreeSurferPipelineBatch.sh
- MSMAll/MSMAllPipeline.sh
- MSMAll/scripts/MSMAll.sh
- PostFreeSurfer/PostFreeSurferPipeline.sh
- PostFreeSurfer/scripts/CreateMyelinMaps.sh
- global/scripts/MyelinMap_BC.sh
There remain several legacy _BC code block that is not replaced by the module `MyelinMap_BC.sh`. 
- replace the old _BC code block in `MSMAll.sh` with `MyelinMap_BC.sh`
- `CreateMyelinMaps.sh` used gifti based _BC which is now replaced by the cifti-based `MyelinMap_BC.sh`, while the gifti files are kept
- add arguments to `PostFreeSurferPipeline.sh` to adapt the module `MyelinMap_BC.sh`
- update the example launch script `PostFreeSurferPipelineBatch.sh`
- change the argument `--myelin-target-file` as a single argument with absolute file path that doesn't depend on `--msm-all-templates`
- MSMAllPipeline logs with no error: 
- `/media/myelin/alex/MSMAll_optimization/MSMAllPipeline.sh.e49165`
- `/media/myelin/alex/MSMAll_optimization/MSMAllPipeline.sh.o49165`
- PostFreeSurferPipeline logs …
> replace the old _BC block with MyelinMap_BC

- tICA/scripts/ComputeTICAFeatures.m
- tICA/scripts/feature_helpers/ComputeDVARSandGS.m
- tICA/scripts/feature_helpers/findFivePercentageOutliers.m
- tICA/scripts/feature_helpers/findOutliers.m
- tICA/scripts/feature_helpers/findScaledMADOutliers.m
- tICA/scripts/feature_helpers/std_outlier.m
- tICA/scripts/feature_helpers/sum_outlier.m
Matlab's `isoutlier` function has new option `percentile` that wasn't introduced in r2017b but in the latest versions. Because of this, the compiled version of Matlab always throws errors for scripts written in r2022 which use commands such as `isoutlier(a, 'percentile', [5,95])`. 
- `isoutlier` and `filloutlier` are removed from the tICA feature generation step
- two custom outlier detection functions are involved, 
- `findFivePercentageOutliers` to find outliers outside 5% to 95% range
- `findScaledMADOutliers` to find outliers three scaled MAD away from the median
- the final outlier is determined by the intersection (AND) between the outliers obtained from the above criteria
In r2022b (raw version),
```
A = [57 59 60 100 59 58 57 58 300 61 62 60 62 58 57]; …
```
> add outlier functions to bypass matlab's isoutlier; adapt to r2017b

- fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
PR for issue https://github.com/Washington-University/HCPpipelines/issues/269
Previously the wildcard search could find directories along with files, the subsequent imcp for copying images/files would then crashed when a directory was provided as an input.
This fix now filters the wildcard search to files only.
> Wildcard search in Volume pipeline no longer finds directories.

- global/scripts/RSNregression.m
- global/scripts/RSNregression.sh
- tICA/scripts/ComputeGroupTICA.m
Introduce a `tICA_weighted` mode which performs the following steps in one mode:
-  weighted spatial regression given a group sICA spatial map;
- tICA unmix given a group tICA mixing matrix;
- single regression to generate individual tICA spatial maps.
> update rsn regression with the tICA regression

- Examples/Scripts/GenericfMRIVolumeProcessingPipelineBatch.sh
- Examples/Scripts/Historical/7T/GenericfMRIVolumeProcessingPipelineBatch.7T.sh
- Examples/Scripts/PreFreeSurferPipelineBatch.sh
- PreFreeSurfer/PreFreeSurferPipeline.sh
- PreFreeSurfer/scripts/T2wToT1wDistortionCorrectAndReg.sh
- fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
- fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
- global/scripts/FieldMapPreprocessingAll.sh
- global/scripts/fsl_version.shlib
Correction of the existing GEHC B0 fieldmap processing (which was incomplete) and implementation of a new B0 fieldmap processing for GEHC data. The minimum required FSL-version is 6.0.7.1 for GEHC B0 fieldmap processing.
The existing fieldmap processing "GeneralElectricFieldMap" was renamed "GEHealthCareLegacyFieldMap". It is made for Legacy existing data converted with dcm2niix (pre-v1.0.20210410). These GEHC B0Maps were a 2 volumes NIFTI file (Volume 1 is the B0Map in Hertz, and Volume 2 the magnitude image).
A new fieldmap processing is introduced and named "GEHealthCareFieldMap". This is intended for new data converted with recent dcm2niix (v1.0.20220720 and later). The GEHC B0Maps are split as 2 NIfTI files (the magnitude and the b0map_fieldmaphz in Hertz - with the suffix …
> Support for GE HealthCare (GEHC) B0 Fieldmap processing.

- DiffusionPreprocessing/DiffPreprocPipeline.sh
- Examples/Scripts/DiffusionPreprocessingBatch.sh
Allows using harmonized time units across pipelines.
> Diffusion echo spacing units

- DiffusionPreprocessing/DiffPreprocPipeline_PreEddy.sh
A user's error log currently looks like this:
```
Image Exception : #63 :: No image files match: /home/<redacted>/projects/HcpPipelines_ExampleData/100307/Diffusion/topup/Pos_b0
No image files match: /home/<redacted>/projects/HcpPipelines_ExampleData/100307/Diffusion/topup/Pos_b0
/home/<redacted>/projects/HCPpipelines/DiffusionPreprocessing/DiffPreprocPipeline_PreEddy.sh: line 177: $1: unbound variable
/home/<redacted>/projects/HCPpipelines/DiffusionPreprocessing/DiffPreprocPipeline_PreEddy.sh: line 334: [: -eq: unary operator expected
Part of FSL (ID: "")
topup
Usage: 
topup --imain=<some 4D image> --datain=<text file> --config=<text file with parameters> --out=my_topup_results
...
Topup::topup_clp::topup_clp: Subsampling levels incompatible with image data.
Wed May  1 18:12:50 JST …
```
> Fix isodd check before Pos_b0 exists

- Examples/Scripts/SetUpHCPPipeline.sh
As of FSL 6.0.6 (release date: 22 nov 2022), the binaries are stored in $FSLDIR/share/fsl/bin, not $FSLDIR/bin
See https://fsl.fmrib.ox.ac.uk/fsl/docs/#/development/history/index?id=_606-22nd-november-2022 for more details
Including $FSLDIR/bin in the $PATH will include all the FSL-specific binaries, but also a lot of other non-FSL related ones. This can lead to confusing behaviour, where FSL versions of generic tools will be used after running `source SetupHCPPipeline.sh` rather than built-in versions.
> Update FSL contribution to PATH

- DiffusionPreprocessing/DiffPreprocPipeline.sh
- DiffusionPreprocessing/DiffPreprocPipeline_Eddy.sh
- DiffusionPreprocessing/DiffPreprocPipeline_PostEddy.sh
- DiffusionPreprocessing/DiffPreprocPipeline_PreEddy.sh
- DiffusionPreprocessing/scripts/DiffusionToStructural.sh
- Examples/Scripts/DiffusionPreprocessingBatch-long.sh
Longitudinal preprocessing saves time by using cross-sectional diffusion eddy_correct output. 
Requirements for the processing directory:
1) Structural timepoints with diffusion preprocessing
2) Longitudinal timepoints with all structural pipelines run
> Diffusion preprocessing longitudinal

- ICAFIX/ReApplyFixMultiRunPipeline.sh
To fix the reclean multi-run pipeline that previously only generated `*_clean.nii.gz` volume output.
> [Reclean] Fix the volume output name and adjust with CleanSubstring

- Examples/Scripts/ReApplyFixMultiRunBatch-long.sh
- ICAFIX/ReApplyFixMultiRunPipeline.sh
- fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
I. Enables longitudinal mode in the ICAFIX pipeline. Only supports multi-run mode. To use:
1) Run all cross-sectional ICAFIX pipelines on each timepoint
2) Longitudinal timepoints require the same sequence of longitudinal pipelines to be run as a pre-requisite, i.e. longitudinal FreeSurfer, PostFreeSurfer, fMRIVolume, and fMRISurface. Then, run ReApplyFixMultiRun pipeline on each longitudinal timepoint, setting the optional --is-longitudinal and --longitudinal-session flags. 
II. Fixes issues to correctly run fMRIVolume pipeline in longitudinal mode on multi-echo runs.
> Longitudinal ICAFix+fMRIVolume multi-echo fix

- ICAFIX/hcp_fix_multi_run
Replace my previous PR with this one. Somehow, when I made fix_3_clean stand alone, I fed it $hp rather than $AlreadyHP. Was not detected because it doesn't matter for hp=0 (typical use case). Now fix_3_clean.m never uses hp.
> Never run hp in fix_3_clean for multirun fix

- Examples/Scripts/RunTICAPipeline_PrecomputedTICA_SubjectCleanBatch-long.sh
- tICA/scripts/tICAMakeCleanLongitudinalTemplate.sh
- tICA/tICAPipeline.sh
Longitudinal adaptation of tICA pipeline. The main difference with the base version is the new script tICAMakeCleanLongitudinalTemplate.sh called in the end of tICAPipeline.sh. This script extracts cleaned fMRI runs from each of the sessions, normalizes variance, re-concatenates across all runs and sessions, and multiplies by session-averaged sICA and tICA cleaned variance. The output is stored under the longitudinal template MNINonLinear/Results folder.
> Longitudinal tICA
